
companies = {
    "Agricultural": [
        {"symbol": "EGAD", "name": "Eaagads Limited"},
        {"symbol": "KUKZ", "name": "Kakuzi Limited"},
        {"symbol": "KAPC", "name": "Kapchorua Tea Company Limited"},
        {"symbol": "LIMT", "name": "Limuru Tea Company Limited"},
        {"symbol": "SASN", "name": "Sasini Tea and Coffee"},
        {"symbol": "WTK", "name": "Williamson Tea Kenya Limited"},
    ],
    "Automobiles and Accessories": [
        {"symbol": "CGEN", "name": "Car & General (Kenya) Limited"},
    ],
    "Banking": [
        {"symbol": "ABSA", "name": "ABSA Bank Kenya"},
        {"symbol": "CFC", "name": "CfC Stanbic Holdings"},
        {"symbol": "DTK", "name": "Diamond Trust Bank Group"},
        {"symbol": "EQTY", "name": "Equity Group Holdings Limited"},
        {"symbol": "HFCK", "name": "Housing Finance Company of Kenya"},
        {"symbol": "IHM", "name": "I&M Holdings Limited"},
        {"symbol": "KCB", "name": "Kenya Commercial Bank Group"},
        {"symbol": "NBK", "name": "National Bank of Kenya"},
        {"symbol": "SCBK", "name": "Standard Chartered of Kenya"},
    ],
    "Commercial and Services": [
        {"symbol": "XPRS", "name": "Express Kenya Limited"},
        {"symbol": "KQ", "name": "Kenya Airways Limited"},
        {"symbol": "NMG", "name": "Nation Media Group Limited"},
        {"symbol": "SGL", "name": "Standard Group Limited"},
        {"symbol": "TPSE", "name": "TPS Eastern Africa (Serena) Limited"},
        {"symbol": "SCAN", "name": "Scangroup Limited"},
        {"symbol": "UCHM", "name": "Uchumi Supermarket Limited"},
        {"symbol": "LKL", "name": "Longhorn Publishers Limited"},
    ],
    "Construction and Allied": [
        {"symbol": "ARM", "name": "Athi River Mining Limited"},
        {"symbol": "BAMB", "name": "Bamburi Cement Limited"},
        {"symbol": "CRWN", "name": "Crown Paints (K) Limited"},
        {"symbol": "CABL", "name": "E.A. Cables Limited"},
        {"symbol": "PORT", "name": "E.A. Portland Cement Co. Limited"},
    ],
    "Energy and Petroleum": [
        {"symbol": "KEGN", "name": "KenGen Limited"},
        {"symbol": "KPLC", "name": "Kenya Power & Lighting Co. Limited"},
        {"symbol": "TOTL", "name": "Total Kenya Limited"},
        {"symbol": "KENO", "name": "KenolKobil Limited"},
        {"symbol": "UMME", "name": "Umeme Limited"},
    ],
    "Insurance": [
        {"symbol": "BRIT", "name": "Britam Holdings Limited"},
        {"symbol": "CIC", "name": "CIC Insurance Group Limited"},
        {"symbol": "JUB", "name": "Jubilee Holdings Limited"},
        {"symbol": "KNRE", "name": "Kenya Re-Insurance Corporation Limited"},
        {"symbol": "LBTY", "name": "Liberty Kenya Holdings Limited"},
        {"symbol": "PAFR", "name": "Pan Africa Insurance Holdings Limited"},
    ],
    "Investment": [
        {"symbol": "CTUM", "name": "Centum Investment Company Limited"},
        {"symbol": "OCH", "name": "Olympia Capital Holdings Limited"},
        {"symbol": "TCL", "name": "Trans-Century Limited"},
    ],
    "Investment Services": [
        {"symbol": "NSE", "name": "Nairobi Securities Exchange Ltd"},
    ],
    "Manufacturing and Allied": [
        {"symbol": "BAUM", "name": "A.Baumann & Co Ltd"},
        {"symbol": "BOC", "name": "B.O.C Kenya Ltd"},
        {"symbol": "BAT", "name": "British American Tobacco Kenya Ltd"},
        {"symbol": "CARB", "name": "Carbacid Investments Ltd"},
        {"symbol": "EABL", "name": "East African Breweries Ltd"},
        {"symbol": "EVRD", "name": "Eveready East Africa Ltd"},
        {"symbol": "ORCH", "name": "Kenya Orchards Ltd"},
        {"symbol": "MSC", "name": "Mumias Sugar Co. Ltd"},
        {"symbol": "UNGA", "name": "Unga Group Ltd"},
    ],
    "Telecommunication and Technology": [
        {"symbol": "SCOM", "name": "Safaricom Limited"},
    ],
    "Growth Enterprise Market Segment (GEMS)": [
        {"symbol": "ATLA", "name": "Atlas Development & Support Services Ltd"},
        {"symbol": "FTGH", "name": "Flame Tree Group Holdings Ltd"},
        {"symbol": "HAFR", "name": "Home Afrika Ltd"},
        {"symbol": "KURV", "name": "Kurwitu Ventures Ltd"},
    ],
}
